#lang racket
;; e：统计每个被 shift 取得的编译期 ctx 的调用次数
(require "cps-count.rkt")
(define (go src)
  (reset-counts!)
  (define c (cps src))
  (printf "源程序: ~s\n编译输出: ~s\n" src c)
  (define tally (make-hash))
  (for ([(tag n) counts])
    (hash-update! tally (list (car tag) n) add1 0))
  (for ([e (sort (hash->list tally) string<? #:key (lambda (p) (format "~a" (car p))))])
    (printf "   ~a 被调用 ~a 次：共 ~a 个\n" (first (car e)) (second (car e)) (cdr e)))
  (newline))
(go '(if a b c))
(go '(add1 (if a b c)))
(go '(f (if a b c)))
(go '(f (if a (if b c d) e)))
(go '(f (if (g a) (h b) (h c))))
(go '(let ([v (reset (let* ([x (shift k 3)] [y (+ 2 x)]) (abort y)))]) (+ 10 v)))
(go '(reset (let ([f (λ (x) (shift k 999))]) (add1 (f 42)))))
